version: "3.9"
services:
  app:
    build:
      context: .  # Указывает на директорию с Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Пробрасываем порт приложения
    volumes:
      - ./library:/libraryManagementApp/library  # Монтируем папку с приложением для разработки
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db  # Указываем, что сервис `app` зависит от сервиса `db`

  db:
    image: postgres:14  # Используем официальный образ PostgreSQL
    environment:
      POSTGRES_USER: user        # Имя пользователя для базы данных
      POSTGRES_PASSWORD: password  # Пароль пользователя
      POSTGRES_DB: mydatabase      # Имя базы данных
    ports:
      - "5432:5432"  # Пробрасываем порт PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Храним данные PostgreSQL в томе

volumes:
  postgres_data:  # Определяем volume для хранения данных PostgreSQL
